In [ ]:
# TMDB EDA Assignment

This project fetches movie data from TMDB API, stores it in SQLite, and performs exploratory data analysis using pandas.

In [3]:
import requests
import pandas as pd
import sqlite3

In [9]:
import requests
import pandas as pd

API_KEY = "1413bba1023e00cdfed7568d823f4617"

url = f"https://api.themoviedb.org/3/discover/movie?api_key={API_KEY}"

response = requests.get(url)

data = response.json()

movies = data['results']

df = pd.DataFrame(movies)

df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,"[10749, 18]",1523145,ru,Твое сердце будет разбито,High school student Polina is saved from bully...,843.1812,/iGpMm603GUKH2SiXB2S5m4sZ17t.jpg,2026-03-26,Your Heart Will Be Broken,False,6.091,11
1,False,/sdZSjtGUTSN8B3al5o0f2WoQfQQ.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,307.5829,/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg,2025-12-17,Avatar: Fire and Ash,False,7.300,1950
2,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,"[878, 12]",687163,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,307.2809,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,Project Hail Mary,False,8.159,645
3,False,/nHxWyy18SvAZ8jJeemtS8k1UNjM.jpg,"[28, 80, 53]",1290821,en,Shelter,A man living in self-imposed exile on a remote...,305.9511,/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg,2026-01-28,Shelter,False,6.728,418
4,False,/6GuqUJ33BnWDAoVPZP55gDr5G55.jpg,"[28, 53, 27]",1084187,en,Pretty Lethal,A troupe of ballerinas find themselves fightin...,308.4196,/znTPnXCK3lEQJgqXCvP7e5FUz6f.jpg,2026-03-13,Pretty Lethal,False,6.806,103

In [11]:
df.describe()

                 id  popularity  vote_average   vote_count
count  2.000000e+01   20.000000     20.000000    20.000000
mean   1.128370e+06  248.661785      6.796800   510.100000
std    3.441553e+05  162.025120      0.949096   648.095177
min    8.353300e+04   83.278500      4.000000     1.000000
25%    1.032097e+06  135.228050      6.210250    66.750000
50%    1.182323e+06  236.209750      6.903000   274.500000
75%    1.305336e+06  306.283550      7.388500   648.250000
max    1.582770e+06  843.181200      8.159000  2370.000000

In [13]:
df.isna().sum()

adult                0
backdrop_path        0
genre_ids            0
id                   0
original_language    0
original_title       0
overview             0
popularity           0
poster_path          0
release_date         0
title                0
video                0
vote_average         0
vote_count           0
dtype: int64

In [15]:
df['genre_ids'].explode().value_counts()

genre_ids
12       7
53       7
35       7
878      6
80       6
28       5
27       5
10751    4
18       3
9648     3
16       3
10749    2
14       1
10752    1
36       1
Name: count, dtype: int64